"""Execution-scoped credential relay for api_key Bindings.

A Capability-based lease, minted from ``secrets``, is issued by the trusted
host for each OpenCode execution.  The lease is bound to exactly one
:class:`~reverse_agent.model_access.contracts.ExecutionSnapshot` and one
relay instance.  The relay is the sole place where the provider master key
is injected upstream; OpenCode only ever sees a loopback relay URL and the
short-lived capability.

The relay rejects:
- any request without a valid, un-expired, non-released lease;
- any method other than ``POST``;
- any path other than ``/chat/completions``;
- any model mismatch against the snapshot;
- non-loopback client origins;
- any request-body or header logging of provider credentials.
"""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from ipaddress import ip_address
import json
import secrets
import threading
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit
from urllib.request import Request, urlopen

from .contracts import ExecutionSnapshot

_MAX_BODY_BYTES = 4 * 1024 * 1024

_HOP_BY_HOP = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailers",
    "transfer-encoding",
    "upgrade",
}


# ---------------------------------------------------------------------------
# Lease
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class ExecutionLease:
    """Short-lived capability issued for one OpenCode execution.

    The lease_id is the high-entropy capability string visible to OpenCode.
    It must be 256-bit (32 bytes) or more, generated by ``secrets.token_urlsafe``.
    """

    lease_id: str
    expires_at: datetime
    relay_url: str
    model_id: str


@dataclass(slots=True)
class _ActiveLease:
    lease_id: str
    snapshot: ExecutionSnapshot
    expires_at: datetime
    relay_url: str
    model_id: str
    used: bool = False
    released: bool = False

    @property
    def expired(self) -> bool:
        return datetime.now(timezone.utc) >= self.expires_at


# ---------------------------------------------------------------------------
# Manager
# ---------------------------------------------------------------------------

class CredentialRelayError(Exception):
    """Fail-closed lease or relay failure."""


class CredentialRelayManager:
    """Owns the lease registry for one trusted host instance.

    Leases are created from an atomic :class:`ExecutionSnapshot`, consumed by
    the relay on request, and released after the subprocess interaction ends.
    """

    def __init__(
        self,
        *,
        default_expiry_seconds: float = 120.0,
        cleanup_margin_seconds: float = 30.0,
    ) -> None:
        if not isinstance(default_expiry_seconds, (int, float)) or default_expiry_seconds <= 0:
            raise CredentialRelayError("invalid_default_expiry")
        if not isinstance(cleanup_margin_seconds, (int, float)) or cleanup_margin_seconds < 0:
            raise CredentialRelayError("invalid_cleanup_margin")
        self._leases: dict[str, _ActiveLease] = {}
        self._lock = threading.RLock()
        self._default_expiry = float(default_expiry_seconds)
        self._cleanup_margin = float(cleanup_margin_seconds)

    def create_lease(
        self,
        snapshot: ExecutionSnapshot,
        *,
        relay_url: str,
        expiry_seconds: float | None = None,
    ) -> ExecutionLease:
        """Create one execution-scoped lease from an atomic snapshot."""
        if snapshot.auth_method != "api_key":
            raise CredentialRelayError("lease_requires_api_key_auth")
        if not snapshot.resolved_api_key:
            raise CredentialRelayError("lease_requires_resolved_secret")

        _validate_loopback_url(relay_url)
        model_id = snapshot.raw_model_id

        expiry = expiry_seconds if expiry_seconds is not None else self._default_expiry
        if not isinstance(expiry, (int, float)) or expiry <= 0:
            raise CredentialRelayError("invalid_expiry_seconds")

        # Lease IDs are prefixed with "sk-" so that OpenCode's built-in
        # OpenAI provider validator accepts them as valid API keys.
        # The remaining 48 bytes are high-entropy URL-safe randomness.
        raw = secrets.token_urlsafe(48)
        assert len(raw) >= 32
        lease_id = "sk-" + raw

        expires_at = datetime.now(timezone.utc) + timedelta(seconds=expiry)

        with self._lock:
            active = _ActiveLease(
                lease_id=lease_id,
                snapshot=snapshot,
                expires_at=expires_at,
                relay_url=relay_url,
                model_id=model_id,
            )
            self._leases[lease_id] = active

        return ExecutionLease(
            lease_id=lease_id,
            expires_at=expires_at,
            relay_url=relay_url,
            model_id=model_id,
        )

    def release_lease(self, lease_id: str) -> None:
        with self._lock:
            active = self._leases.pop(lease_id, None)
            if active is not None:
                active.released = True
            self._cleanup_locked()

    def release_all(self) -> None:
        with self._lock:
            for active in self._leases.values():
                active.released = True
            self._leases.clear()

    def _validate_lease_for_request(
        self,
        lease_id: str,
        *,
        method: str,
        path: str,
        model: str | None,
    ) -> _ActiveLease:
        with self._lock:
            active = self._leases.get(lease_id)
            if active is None:
                raise CredentialRelayError("lease_not_found")
            if active.released:
                raise CredentialRelayError("lease_released")
            if active.expired:
                raise CredentialRelayError("lease_expired")
            self._cleanup_locked()

        if method.upper() != "POST":
            raise CredentialRelayError(f"lease_method_mismatch:{method}")
        if path != "/chat/completions":
            raise CredentialRelayError(f"lease_path_mismatch:{path}")
        expected_model = active.model_id
        if model is None or model != expected_model:
            raise CredentialRelayError("lease_model_mismatch")
        return active

    def _cleanup_locked(self) -> None:
        expired_ids = [
            lid for lid, a in self._leases.items() if a.expired
        ]
        for lid in expired_ids:
            del self._leases[lid]

    # Public introspection for tests (does not leak secrets)
    def lease_count(self) -> int:
        with self._lock:
            self._cleanup_locked()
            return len(self._leases)

    def has_active_lease(self, lease_id: str) -> bool:
        with self._lock:
            active = self._leases.get(lease_id)
            return active is not None and not active.expired and not active.released


# ---------------------------------------------------------------------------
# Upstream relay
# ---------------------------------------------------------------------------

def _http_roundtrip(
    url: str,
    method: str,
    body: bytes,
    headers: dict[str, str],
    timeout: float,
) -> tuple[int, bytes, dict[str, str]]:
    req = Request(url, data=body, headers=headers, method=method)
    req.full_url = url
    try:
        with urlopen(req, timeout=timeout) as resp:  # noqa: S310 - gated relay
            status = int(resp.status)
            resp_headers = {k.lower(): v for k, v in resp.getheaders()}
            data = resp.read(_MAX_BODY_BYTES)
            return status, data, resp_headers
    except HTTPError as exc:
        body = exc.read(_MAX_BODY_BYTES)
        headers = {k.lower(): v for k, v in exc.headers.items()} if exc.headers else {}
        return int(exc.code), body, headers
    except (URLError, TimeoutError, OSError) as exc:
        raise CredentialRelayError(f"upstream_error:{exc.__class__.__name__}") from exc


def forward_to_upstream(
    active: _ActiveLease,
    *,
    body: bytes,
    timeout: float = 120.0,
) -> tuple[int, bytes, dict[str, str]]:
    """Inject provider Authorization and forward to the frozen upstream URL."""
    _validate_upstream_url(active.snapshot.base_url)
    upstream_url = f"{active.snapshot.base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {active.snapshot.resolved_api_key}",
        "Content-Type": "application/json",
        "Content-Length": str(len(body)),
        "Accept": "application/json, text/event-stream",
    }
    return _http_roundtrip(upstream_url, "POST", body, headers, timeout)


# ---------------------------------------------------------------------------
# Streamed (SSE) relay
# ---------------------------------------------------------------------------

def stream_sse(
    active: _ActiveLease,
    *,
    body: bytes,
    wfile: Any,
    timeout: float = 120.0,
) -> int:
    """Forward request and relay raw SSE response directly to the client wfile.

    Pure passthrough: no fabricated status events, no extra [DONE], no
    newline injection, no payload transformation. The upstream stream is
    read in bounded chunks and flushed to the client in upstream order.
    """
    _validate_upstream_url(active.snapshot.base_url)
    upstream_url = f"{active.snapshot.base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {active.snapshot.resolved_api_key}",
        "Content-Type": "application/json",
        "Content-Length": str(len(body)),
        "Accept": "text/event-stream",
    }
    req = Request(upstream_url, data=body, headers=headers, method="POST")
    req.full_url = upstream_url
    try:
        with urlopen(req, timeout=timeout) as resp:  # noqa: S310
            status = int(resp.status)
            chunk_size = 4096
            while True:
                chunk = resp.read(chunk_size)
                if not chunk:
                    break
                wfile.write(chunk)
                wfile.flush()
            return status
    except HTTPError as exc:
        return int(exc.code)
    except (URLError, TimeoutError, OSError) as exc:
        raise CredentialRelayError(f"upstream_error:{exc.__class__.__name__}") from exc


# ---------------------------------------------------------------------------
# Relay HTTP handler
# ---------------------------------------------------------------------------

class _RelayHandler(BaseHTTPRequestHandler):
    manager: CredentialRelayManager
    upstream_timeout: float = 120.0

    server_version = "reverse-agent-relay/1"
    sys_version = ""

    def log_message(self, format: str, *args: object) -> None:
        return

    def do_POST(self) -> None:  # noqa: N802
        if not self._check_loopback():
            self._send_error(403, "relay_forbidden")
            return

        lease_id = self._extract_lease_id()
        if not lease_id:
            self._send_error(400, "missing_lease")
            return

        body = self._read_body()
        if body is None:
            self._send_error(400, "invalid_body")
            return

        request_path = urlsplit(self.path).path
        if request_path != "/chat/completions":
            self._send_error(404, "relay_route_not_found")
            return

        try:
            payload = json.loads(body.decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            self._send_error(400, "invalid_json")
            return
        if not isinstance(payload, dict):
            self._send_error(400, "invalid_json")
            return

        request_model = payload.get("model")
        try:
            active = self.manager._validate_lease_for_request(
                lease_id,
                method="POST",
                path="/chat/completions",
                model=request_model,
            )
        except CredentialRelayError:
            self._send_error(401, "lease_invalid")
            return

        try:
            accept = self.headers.get("Accept", "")
            if "text/event-stream" in accept:
                self._relay_sse_fail_closed(active, body)
                return
            status, response_body, _resp_headers = forward_to_upstream(
                active,
                body=body,
                timeout=self.upstream_timeout,
            )
        except CredentialRelayError:
            self._send_error(502, "upstream_error")
            return

        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(response_body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(response_body)

    def do_GET(self) -> None:  # noqa: N802
        if not self._check_loopback():
            self._send_error(403, "relay_forbidden")
            return
        if self.path == "/health":
            self._send_json(200, {"status": "relay_healthy"})
            return
        self._send_error(405, "relay_method_not_allowed")

    def _extract_lease_id(self) -> str | None:
        auth = self.headers.get("Authorization", "")
        if auth.lower().startswith("bearer "):
            token = auth[len("bearer "):].strip()
            if token:
                return token
        return None

    def _read_body(self) -> bytes | None:
        raw = self.headers.get("Content-Length")
        if raw is None:
            return b""
        try:
            length = int(raw)
        except (ValueError, TypeError):
            return None
        if length < 0 or length > _MAX_BODY_BYTES:
            return None
        return self.rfile.read(length)

    def _check_loopback(self) -> bool:
        addr = getattr(self, "client_address", None)
        if addr and isinstance(addr, tuple) and addr[0]:
            host = addr[0]
            try:
                address = ip_address(host)
                return address.is_loopback
            except ValueError:
                return host.lower() in ("localhost",)
        return False

    def _send_error(self, code: int, reason: str) -> None:
        body = json.dumps({"error": reason}, separators=(",", ":")).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _send_sanitized_error(self, code: int) -> None:
        body = json.dumps({"error": "upstream_error"}, separators=(",", ":")).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _relay_sse_fail_closed(self, active: _ActiveLease, body: bytes) -> None:
        _validate_upstream_url(active.snapshot.base_url)
        upstream_url = f"{active.snapshot.base_url}/chat/completions"
        headers = {
            "Authorization": f"Bearer {active.snapshot.resolved_api_key}",
            "Content-Type": "application/json",
            "Content-Length": str(len(body)),
            "Accept": "text/event-stream",
        }
        req = Request(upstream_url, data=body, headers=headers, method="POST")
        req.full_url = upstream_url
        try:
            with urlopen(req, timeout=self.upstream_timeout) as resp:  # noqa: S310
                status = int(resp.status)
                if status != 200:
                    self._send_sanitized_error(status)
                    return
                self.send_response(200)
                self.send_header("Content-Type", "text/event-stream")
                self.send_header("Cache-Control", "no-store")
                self.end_headers()
                while True:
                    chunk = resp.read(4096)
                    if not chunk:
                        break
                    self.wfile.write(chunk)
                    self.wfile.flush()
        except HTTPError as exc:
            self._send_sanitized_error(int(exc.code))
        except (URLError, TimeoutError, OSError):
            self._send_error(502, "upstream_error")

    def _send_json(self, code: int, payload: dict[str, Any]) -> None:
        body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


# ---------------------------------------------------------------------------
# Relay server
# ---------------------------------------------------------------------------

def _validate_loopback_url(value: str) -> None:
    parsed = urlsplit(value.strip())
    if parsed.scheme not in {"http", "https"}:
        raise CredentialRelayError("relay_url_invalid")
    host = (parsed.hostname or "").casefold()
    if host == "localhost":
        return
    try:
        address = ip_address(host)
    except ValueError:
        raise CredentialRelayError("relay_url_not_loopback")
    if not address.is_loopback:
        raise CredentialRelayError("relay_url_not_loopback")


def _validate_upstream_url(base_url: str) -> None:
    """Fail closed on non-loopback cleartext HTTP upstream URLs.

    HTTPS is allowed for any host. HTTP is only allowed for exact loopback
    addresses (127.0.0.1, ::1, localhost). No DNS resolution is performed;
    the boundary is determined purely from the URL hostname.
    """
    parsed = urlsplit(base_url.strip())
    if parsed.scheme == "https":
        return
    if parsed.scheme == "http":
        host = (parsed.hostname or "").casefold()
        if host == "localhost":
            return
        try:
            address = ip_address(host)
        except ValueError:
            raise CredentialRelayError("upstream_cleartext_not_loopback")
        if address not in {ip_address("127.0.0.1"), ip_address("::1")}:
            raise CredentialRelayError("upstream_cleartext_not_loopback")
        return
    raise CredentialRelayError("upstream_url_invalid")


def _normalize_model_id(provider: str, model_id: str) -> str:
    if "/" not in model_id:
        return f"{provider}/{model_id}"
    return model_id


def run_credential_relay_server(
    *,
    manager: CredentialRelayManager,
    host: str = "127.0.0.1",
    port: int = 0,
    upstream_timeout: float = 120.0,
) -> ThreadingHTTPServer:
    handler_cls = type(
        "_RelayHandler",
        (_RelayHandler,),
        {"manager": manager, "upstream_timeout": upstream_timeout},
    )
    server = ThreadingHTTPServer((host, port), handler_cls)
    return server


class CredentialRelayServer:
    """Context-managed relay server bound to a fresh loopback port."""

    def __init__(
        self,
        manager: CredentialRelayManager,
        *,
        host: str = "127.0.0.1",
        port: int = 0,
        upstream_timeout: float = 120.0,
    ) -> None:
        self.manager = manager
        self._host = host
        self._port = port
        self._upstream_timeout = upstream_timeout
        self._server: ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None
        self.url = ""

    def __enter__(self) -> "CredentialRelayServer":
        self._server = run_credential_relay_server(
            manager=self.manager,
            host=self._host,
            port=self._port,
            upstream_timeout=self._upstream_timeout,
        )
        self._port = self._server.server_address[1]
        self.url = f"http://{self._host}:{self._port}"
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):  # noqa: N802,N803
        if self._server:
            self._server.shutdown()
        if self._thread:
            self._thread.join(timeout=3.0)
        return False